name: Release desktop

#on:
#  push:
#    tags:
#      - 'v*'  # This will trigger the workflow on push to tags like v1.0, v2.0, etc.

on:
  push:
    branches:
      - "master"

jobs:
  build-windows:
    name: Build Windows binaries
    runs-on: windows-latest
    environment: production
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
          override: true

      - name: Install Dependencies
        run: npm ci

      - name: Build Tauri App
        run: npm run tauri-build

      - name: Upload Windows portable exe
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: |
            ./frontend/src-tauri/target/release/**/*.msi
            ./frontend/src-tauri/target/release/**/*.exe
          

  publish:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Download the previously uploaded artifacts
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: exe
          path: exe
      # And create a release with the artifacts attached
      - name: 'create release'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          draft: true
          files: ./exe/**/*
